version: '3.1'

services:
  postgres:
    container_name: postgres-container
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ecommerce-restful-api
