spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/ecommerce-restful-api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    password: test
    username: test
    host: 127.0.0.1
    port: 3025 # default protocol port + 3000 as offset
    protocol: smtp
    test-connection: false # avoid setting this to true when using a per-test-method GreenMail server

custom:
  jwt:
    secret: this-isk2;3429wweyurpowuerwuieoihfwer9w8e9r2
  api-domain: localhost
  stacktrace:
    enabled: true
  account-activation:
    url: http://localhost:5173/activate-account
  password-reset:
    url: http://localhost:5173/reset-password
