CREATE TABLE users(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    email      VARCHAR(50) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    phone      VARCHAR(10) DEFAULT NULL,
    role       VARCHAR(50) NOT NULL,
    enabled    BOOLEAN NOT  NULL DEFAULT FALSE,
    non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    using_mfa  BOOLEAN NOT NULL DEFAULT FALSE,
    image_url  VARCHAR(255) NOT NULL DEFAULT 'https://cdn-icons-png.flaticon.com/512/149/149071.png',
    CONSTRAINT UQ_users_email UNIQUE (email),
    PRIMARY KEY (id)
);
