CREATE TABLE account_activation_tokens(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    PRIMARY KEY (id)
);
